/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asak;

import java.sql.ResultSet;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author bansh
 */
public class Billpad extends javax.swing.JFrame {
    static int currentUnit = 0;
    static FileWriter fw;
    static int unitConsumed;
    static float amt1 = 0, amt2 = 0, amt3 = 0, amt4 = 0;


    public Billpad(String u) {
        super("Consumer Bill");
        
        initComponents();
        Billpad1.setText(u);
        Billpad1.setEditable(false);
    }
     public static void calculateBill(){
        if (unitConsumed>=150){
            amt1 = 150*6;
            if (unitConsumed >= 300){
                amt2 = 150*5.5f;
                if (unitConsumed >= 500){
                    amt3 = 200*6.5f;
                    amt4 = (unitConsumed-500)*7;
                }
                else{
                    amt3 = (unitConsumed-300)*6.6f;
                }
            }
            else{
                amt2 = (unitConsumed-150)*5.5f;
            }
        }
        else{
            amt1 = unitConsumed*6;
        }
        
    }
    
    public float billingData(ResultSet rs){
        writeBill(rs);
        this.setVisible(true);
        return unitConsumed;
    }
    
    private void writeBill(ResultSet rs){
        
        try{
            rs.next();
            int unit = rs.getInt(9);
            unitConsumed = (currentUnit-unit);
            if (unitConsumed < 0 ) unitConsumed = 0;
            String s =  "-------------------------------------------\n" +
                        "              ASAK_SOLUTIONS               \n" +
                        "-------------------------------------------\n" +
                        "\n" +
                        "Meter No.: "+rs.getString(8) + "\n" +
                        "Name     : "+rs.getString(3) + "\n" +
                        "Address  : "+rs.getString(4) + "\n" +
                        "Phone no.: "+rs.getString(7) + "\n" +
                        "\n" +
                        "-------------------------------------------\n" +
                        "\n";
                        calculateBill();
                   s += "First 150 units Costs @ Rs.6.0 : Rs." + amt1 + "\n" +
                        "Next 150 units Costs @ Rs.5.5  : Rs." + amt2 + "\n" +
                        "Next 200 units Costs @ Rs.6.5  : Rs." + amt3 + "\n" +
                        "Next 107 units Costs @ Rs.7.0  : Rs." + amt4 + "\n" +
                        "\n" +
                        "-------------------------------------------\n" +
                        "\n" +
                        "Unit Used: " + unitConsumed +
                        "\n" +
                        "Total Amount: Rs." + (amt1+amt2+amt3+amt4) +
                        "\n";
            Billpad1.setText(s);
        }catch(SQLException cerr){
            System.out.println(cerr);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Billpad1 = new javax.swing.JTextArea();
        print = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Billpad1.setColumns(20);
        Billpad1.setRows(5);
        jScrollPane1.setViewportView(Billpad1);

        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer (1).png"))); // NOI18N
        print.setBorder(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.jpg"))); // NOI18N
        jButton1.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(print)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(print)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billpad("1").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Billpad1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables
}
